In [2]:
#递归方法  打家劫舍（只能取相邻的，找最大值）
def rec_dp(arr, i):
    if i == 0:
        return arr[i]
    elif i == 1:
        return max(arr[0], arr[1])
    else:
        A = rec_dp(arr, i-2) + arr[i] #选中当前这个值，结果是当前值加上i-2时的最优值
        B = rec_dp(arr, i-1)
        return max(A, B)
rec_dp([1,2,4,1,7,8,3], 6)

15

In [4]:
#由于递归方法复杂度高2**n （由于不存中间数，每个都重新计算） 一般改成不是递归的
import numpy as np
def dp(arr):
    opt = np.zeros(len(arr))
    opt[0] = arr[0]
    opt[1] = max(arr[0], arr[1])
    for i in range(2, len(arr)):
        A = opt[i-2] + arr[i]
        B = opt[i-1]
        opt[i] = max(A, B)
    print(opt)
    return opt[i]
dp([1,2,4,1,7,8,3])

[  1.   2.   5.   5.  12.  13.  15.]


15.0

In [9]:
##斐波那契数列 [1,1,2,3,5,8]
def fib(i):
    if i == 0 or i == 1:
        return 1
    else:
        return fib(i-1) + fib(i-2)
fib(5)

8

In [19]:
# import numpy as np
def fib1(i):
    i = i+1
    opt = np.zeros(i)
    opt = [0 for _ in range(i)]
    opt[0], opt[1] = 1,1
    for k in range(2, i):
        opt[k] = opt[k-1] + opt[k-2]
    print(opt)
    return opt[k]
fib1(5)

[1, 1, 2, 3, 5, 8]


8

In [4]:
# k_sum 是否存在数加起来可以得到target
def k_sum(nums, i, target):
    if target == 0:
        return True
    elif i == 0:
        return nums[i] == target
    elif nums[i] > target:
        return k_sum(nums, i-1, target)
    else:
        A = k_sum(nums, i-1, target)
        B = k_sum(nums, i-1, target - nums[i])
        return A or B
    
    
def k_sum2(nums, target):
    import numpy as np
    subset = np.zeros((len(nums), target+1), dtype=bool)
    subset[:, 0] = True
    
    subset[0, :] = False
    subset[0, nums[0]] = True
    subset[0, 0] = True
    for i in range(1, len(nums)):
        for s in range(1, target+1):
            if nums[i] > s:
                subset[i, s] = subset[i-1, s]
            else:
                A = subset[i-1, s]
                B = subset[i-1, s-nums[i]]
                subset[i, s] = A or B
#     print(subset)
    return subset[i, s]
print(k_sum([3, 34, 4, 12, 5, 2],  5, 9))
print(k_sum([3, 34, 4, 12, 5, 2],  5, 10))
print(k_sum([3, 34, 4, 12, 5, 2],  5, 11))
print(k_sum([3, 34, 4, 12, 5, 2],  5, 12))
print(k_sum([3, 34, 4, 12, 5, 2],  5, 13))

print(k_sum2([3, 34, 4, 12, 5, 2], 9))
print(k_sum2([3, 34, 4, 12, 5, 2], 10))
print(k_sum2([3, 34, 4, 12, 5, 2], 11))
print(k_sum2([3, 34, 4, 12, 5, 2], 12))
print(k_sum2([3, 34, 4, 12, 5, 2], 13))

True
True
True
True
False
True
True
True
True
False


In [32]:
#自己觉得这样就可以 ，有待验证
def k_sum(nums, sum_):
    dp = np.zeros((len(nums)+1, sum_+1), dtype=bool)
    dp[:, 0] = True
#     dp[1, nums[0]] = True
    for i in range(1, len(nums)+1):
        for j in range(1, sum_+1):
            if  j < nums[i-1]:
                dp[i][j] = dp[i-1][j]
            else:
                dp[i][j] = dp[i-1, j-nums[i-1]] or dp[i-1, j]
    return dp[-1][-1]
#     print(dp)
print(k_sum([3, 34, 4, 12, 5, 2], 9))
print(k_sum([3, 34, 4, 12, 5, 2], 10))
print(k_sum([3, 34, 4, 12, 5, 2], 11))
print(k_sum([3, 34, 4, 12, 5, 2], 12))
print(k_sum([3, 34, 4, 12, 5, 2], 13))
print(k_sum([3], 3))
    

True
True
True
True
False
True


## dfs， bfs

## 


![title](img/2.jpg)

In [3]:
graph = {'A': ['B', 'C'],   #图用字典表示
         'B': ['A', 'C', 'D'], 
         'C': ['A', 'B', 'D', 'E'], 
         'D': ['B', 'C', 'E', 'F'], 
         'E':['C', 'D'], 
         'F':['D']}

In [12]:
def bfs(graph, s):  #建立一个队列 只有队列有节点，pop出来节点 然后看他的所有连接节点，如果是没见过的节点
    queue = []      #就append到stack里面 
    queue.append(s)
    seen_node = [s]
    while queue:
        node = queue.pop(0)
        for node_single in graph[node]:
            if node_single not in seen_node:
                queue.append(node_single)
                seen_node.append(node_single)
        print(node, end='')
bfs(graph, 'A')
print('')
bfs(graph, 'E')

ABCDEF
ECDABF

In [18]:
def dfs(graph, s):  #直接把队列改成栈就完事了，别的啥都不用改
    stack = [s]  
    seen_node = [s]
    while stack:
        node = stack.pop()
        for node_single in graph[node]:
            if node_single not in seen_node:
                stack.append(node_single)
                seen_node.append(node_single)
        print(node, end='')   
dfs(graph, 'A')
print('')
dfs(graph, 'E')

ACEDFB
EDFBAC

In [34]:
def dfs(graph, s):   #拓展， 寻找最短路径
    stack = [s]  
    seen_node = [s]
    parent = {s: None}
    while stack:
        node = stack.pop(0)    # ######### 加0 是E -> C -> B 不加0 是 E -> D -> B
        for node_single in graph[node]:
            if node_single not in seen_node:
                stack.append(node_single)
                seen_node.append(node_single)
                parent[node_single] = node
        print(node, end='')   
    return parent
# dfs(graph, 'A')
# print('')
parent = dfs(graph, 'E')  #得到储存所有上一步节点的字典  算E -> B的最短路径
print('') 
print(parent)
# for i, j in parent.items():
#     print(i, j)
v = 'B'
while v!=None:
    print(v)
    v = parent[v]
    

ECDABF
{'E': None, 'C': 'E', 'D': 'E', 'A': 'C', 'B': 'C', 'F': 'D'}
B
C
E


## 带距离的最短路径

![title](img/1.png)

In [37]:
import heapq
graph = {'A': {'B':5, 'C':1},   #图用字典表示
         'B': {}'A':5, 'C', 'D'}, 
         'C': ['A', 'B', 'D', 'E'], 
         'D': ['B', 'C', 'E', 'F'], 
         'E':['C', 'D'], 
         'F':['D']}


In [39]:
a = []
heapq.heappush(a, (3, 'A'))
a

[(3, 'A')]

In [51]:
import heapq
import math
graph = {'A': {'B':5, 'C':1},   #图用字典表示
         'B': {'A':5, 'C':2, 'D':1}, 
         'C': {'A':1, 'B':2, 'D':4, 'E':8}, 
         'D': {'B':1, 'C':4, 'E':3, 'F':6}, 
         'E':{'C':8, 'D':3}, 
         'F':{'D':6}}

def init_distance(graph, s):
	distance = {s:0}
	for i in graph.keys():
		if i is not s:
			distance[i] = math.inf
	return distance

def short_path(graph, s):
	pqueue = []
	heapq.heappush(pqueue, (0, s))
	parent = {s:None}
	distance = init_distance(graph, s)
	seen = []
	while pqueue:
		dist, vertex = heapq.heappop(pqueue)
		seen.append(vertex)  #只能说明父节点处理过了，每个子节点都要再处理 
		for w in graph[vertex].keys():
			if w not in seen:
				if dist + graph[vertex][w] < distance[w]:
					distance[w] = dist + graph[vertex][w]
					heapq.heappush(pqueue, (dist+graph[vertex][w], w))
					parent[w] = vertex
	return parent, distance
parent, distance = short_path(graph, 'A')
print(parent)
print(distance)

{'A': None, 'B': 'C', 'C': 'A', 'D': 'B', 'E': 'D', 'F': 'D'}
{'A': 0, 'B': 3, 'C': 1, 'D': 4, 'E': 7, 'F': 10}


In [50]:
## 求出内个最短的路径  （这是反向的）
v = 'F' 
while v is not None:
    print(v)
    v = parent[v]

F
D
B
C
A


In [11]:
def maxSubArray(nums):  
    """ 
    :type nums: List[int] 
    :rtype: int 
    """  
    length=len(nums)  
    for i in range(1,length):  
        #当前值的大小与前面的值之和比较，若当前值更大，则取当前值，舍弃前面的值之和  
        subMaxSum=max(nums[i]+nums[i-1],nums[i])  
        nums[i]=subMaxSum#将当前和最大的赋给nums[i]，新的nums存储的为和值  
    print(nums)
    return max(nums) 
maxSubArray([1,2,-2,4,1])

[1, 3, 1, 5, 6]


6

In [8]:
def max_sub(nums):
    cur_sum = 0
    max_sum = nums[0]
    for i in range(len(nums)):
        cur_sum += nums[i]
        max_sum = max(cur_sum, max_sum)
        if cur_sum < 0: #如果当前和<0 说明前面全不能用
            cur_sum = 0
        print(max_sum)
max_sub([1,2,-2,4,-2, 1])

1
3
3
5
5
5


In [27]:
# 最大正方形  需要维护3个数组  向上的0的个数 向左的0的个数 左上角的边长  边长+1和他们两个的最小值
def max_square(nums):
    raw = len(nums)
    col = len(nums[0])
    dp = [[0 for j in range(col)] for i in range(raw)]
    for i in range(raw):
        for j in range(col):
            dp[i][j] = int(nums[i][j])
    up = [[0 for i in range(col)] for _ in range(raw)]
    left = [[0 for i in range(col)] for _ in range(raw)]
    for i in range(len(nums)):
        for j in range(len(nums[0])):
            l_value = 0
            u_value = 0
            k = j
            while k>=0 and nums[i][k] == '1':
                k -= 1
                l_value += 1
            left[i][j] = l_value
            q = i
            while q>=0 and nums[q][j] == '1':
                q -= 1
                u_value += 1
            up[i][j] = u_value
    dp[0][0] = int(nums[0][0])
    for i in range(1, raw):
        for j in range(1, col):
            dp[i][j] = min(dp[i-1][j-1]+1, left[i][j], up[i][j])
#     print(left)
#     print(up)
#     print(dp)
    return max(max(dp, key=max))**2

# max_square([["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]])
max_square([
  ["1","0","1","0","0"],
  ["1","0","1","1","1"],
  ["1","1","1","1","1"],
  ["1","0","0","1","0"]
])
max_square([["0","1"]])
#     for i in range()

1

In [1]:
#猜数字2  最小需要钱数猜出来  TL 递归方式不行
def getMoneyAmount(n):
    def inner(dp, i, j):
#         print(i, j)
        if i >= j:
            return 0
        elif dp[i][j]:  #如果已经更改过，就可以不动了，加上这个可以少运行一些
            return dp[i][j]
        else:
            dp[i][j] = float('inf')
            for k in range(i, j):
                left = inner(dp, i, k-1)
                right = inner(dp, k+1, j)
                temp = max(left, right) + k #选左边和右边中大的费用（最少花费）
                dp[i][j] = min(temp, dp[i][j]) 
            return dp[i][j]
    dp = [[0 for _ in range(n+1)] for _ in range(n+1)]
    inner(dp, 1, n)
#     print(dp)
    return dp[1][n]
getMoneyAmount(10)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 2, 4, 6, 8, 10, 12, 0, 16], [0, 0, 0, 2, 3, 6, 8, 10, 12, 0, 16], [0, 0, 0, 0, 3, 4, 8, 10, 12, 0, 16], [0, 0, 0, 0, 0, 4, 5, 10, 12, 0, 16], [0, 0, 0, 0, 0, 0, 5, 6, 12, 0, 16], [0, 0, 0, 0, 0, 0, 0, 6, 7, 0, 16], [0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 16], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


16

In [2]:
def getMoneyAmount(n): #改成迭代方式
    """
    :type n: int
    :rtype: int
    """
    need = [[0] * (n + 1) for _ in range(n + 1)]
    for low in range(n, 0, -1):
        for high in range(low + 1, n + 1):
            print(low, high)
            need[low][high] = min(x + max(need[low][x-1], need[x+1][high]) for x in range(low, high))
    print(need)
    return need[1][n]
getMoneyAmount(4) 

3 4
2 3
2 4
1 2
1 3
1 4
[[0, 0, 0, 0, 0], [0, 0, 1, 2, 4], [0, 0, 0, 2, 3], [0, 0, 0, 0, 3], [0, 0, 0, 0, 0]]


4

## 01 背包问题

In [16]:
def pack1(w, v, C): #每个东西只能选择一次
    dp = [[0 for _ in range(C+1)] for _ in range(len(w)+1)]
    for i in range(1, len(w)+1):
        for j in range(1, C+1):
            if j < w[i-1]:
                dp[i][j] = dp[i-1][j]
            else:
                dp[i][j] = max(dp[i-1][j], dp[i-1][j-w[i-1]]+ v[i-1])
#     print(dp)
    for i in dp:
        print(i)
# pack1([2,2,6,5,4], [6,3,5,4,6], 10)
# print('')
pack1([2,3,4,5], [3,4,5,6], 8)

[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 3, 3, 3, 3, 3, 3, 3]
[0, 0, 3, 4, 4, 7, 7, 7, 7]
[0, 0, 3, 4, 5, 7, 8, 9, 9]
[0, 0, 3, 4, 5, 7, 8, 9, 10]


In [16]:
def pack1(w, v, C): #初始化不同，这种需要枚举最大值
                    #代表的是把容量恰好用完
    dp = [[float('-inf') for _ in range(C+1)] for _ in range(len(w)+1)]
    for i in range(len(w)+1):
        for j in range(C+1):
            if j==0:
                dp[i][j] = 0
    for i in range(1, len(w)+1):
        for j in range(1, C+1):
            if j < w[i-1]:
                dp[i][j] = dp[i-1][j]
            else:
                dp[i][j] = max(dp[i-1][j], dp[i-1][j-w[i-1]]+ v[i-1])
    for i in dp:
        print(i)
# pack1([2,2,6,5,4], [6,3,5,4,6], 10)
# print('')
pack1([2,3,4,5], [3,4,5,6], 8)

[0, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf]
[0, -inf, 3, -inf, -inf, -inf, -inf, -inf, -inf]
[0, -inf, 3, 4, -inf, 7, -inf, -inf, -inf]
[0, -inf, 3, 4, 5, 7, 8, 9, -inf]
[0, -inf, 3, 4, 5, 7, 8, 9, 10]


In [19]:
def pack2(w, v, C): #每个东西能选择多次 完全背包问题
    dp = [[0 for _ in range(C+1)] for _ in range(len(w)+1)]
    for i in range(1, len(w)+1):
        for j in range(1, C+1):
            if j < w[i-1]:
                dp[i][j] = dp[i-1][j]
            else:
                dp[i][j] = max(dp[i-1][j], dp[i][j-w[i-1]]+ v[i-1]) #只是把这列dp[i-1]... -> dp[i]...
#     print(dp)                                                     #可以选择的东西数量不变，重量减去选择一件后
    for i in dp:
        print(i)
# pack1([2,2,6,5,4], [6,3,5,4,6], 10)
# print('')
pack2([2,3,4,5], [3,4,5,6], 8)

[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 3, 3, 6, 6, 9, 9, 12]
[0, 0, 3, 4, 6, 7, 9, 10, 12]
[0, 0, 3, 4, 6, 7, 9, 10, 12]
[0, 0, 3, 4, 6, 7, 9, 10, 12]


In [27]:
# 如果我们想知道n=15的方法数，我们可以转换为求n=14的方法数、n=11的方法数
# n=6的方法数,然后他们中间取最小值+1，即是15的方法数。
#TL 超时   JAVA打败60%
#所有平方数加起来， 使用平方数数量最少
import math
def prefect_square(n):
    op = [float('inf') for _ in range(n+1)]
    for i in range(n+1):
        if is_square(i):
            op[i] = 1
        j = 1
        while j * j < i:
            op[i] = min(op[i-j*j] + 1, op[i])
            j += 1
    print(op)
    return op[-1]
def is_square(n):
    ret = int(math.sqrt(n))
    return ret * ret == n
prefect_square(13)
# print(is_square(4))

[1, 1, 2, 3, 1, 2, 3, 4, 2, 1, 2, 3, 3, 2]


2

In [53]:
#300 最长上升子序列   [10,9,2,5,3,7,101,18] 输出: 4 解释: 最长的上升子序列是 [2,3,7,101]，它的长度是 4。
def lengthOfLIS(nums):
    if not nums:
        return 0
    dp = [1 for _ in range(len(nums))]
    ret = 1
    for i in range(1, len(nums)):
        max_dp = 0
        for j in range(i):
            if nums[j] < nums[i]:   # 对nums[i]操作的时候 跟每个之前的值比较，如果小就进行操作
                max_dp = max(max_dp, dp[j])# 找到小于这个值得所有dp值中最大的 ，给他加1
        dp[i] = max_dp + 1
        ret = max(ret, dp[i]) #dp不是前i个最长上升，是以第i元素为结尾的最长子序列
    print(dp)
    return ret
lengthOfLIS([4,10,4,3,8,9, 1])
# long_as([0])

[1, 2, 1, 1, 2, 3, 1]


3

In [22]:
def k_sum(nums, target): #背包问题稍微改一改就能解决k_sum问题  吧重量和价值变成一样，返回最后一个数==target
    import numpy as np  #前i个元素能组成的最大数（重量）（在最接近给定重量的情况下）
    dp = np.zeros((len(nums)+1, target+1))#比如说dp[4,5] 可选4个物体，容量最大的5情况下得到的价值最大，这里容量
#     dp[:, 0] = True                    #和价值相等，就<=5中最大的，如果==5的话 就说明正好能取到5，能找到数加起来
#     dp[1, nums[0]] = True             #等于5
    for i in range(1, len(nums)+1):
        for j in range(1, target+1):
            if j < nums[i-1]:
                dp[i, j] = dp[i-1, j]
            else:
                dp[i, j] = max(dp[i-1, j-nums[i-1]]+nums[i-1], dp[i-1, j])
    print(dp)
    return dp[-1][-1] == target
# print(k_sum([1,2,3, 5, 9], 1))
print(k_sum([1,3, 5, 9], 13))
# print(k_sum([1,2,3, 5, 9], 12))
# print(k_sum([1,2,3, 5, 9], 11))

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.   1.   3.   4.   4.   4.   4.   4.   4.   4.   4.   4.   4.]
 [  0.   1.   1.   3.   4.   5.   6.   6.   8.   9.   9.   9.   9.   9.]
 [  0.   1.   1.   3.   4.   5.   6.   6.   8.   9.  10.  10.  12.  13.]]
True


In [21]:
#416. 分割等和子集   TL解法 JAVA通过
def canPartition(nums):
    """
    :type nums: List[int]
    :rtype: bool
    """
    target = sum(nums)
    if target % 2 == 1:
        return False
    else:
        target = int(target/2)
        dp = [[0 for _ in range(target+1)] for _ in range(len(nums)+1)]
        for i in range(1, len(nums)+1):
            for j in range(1, target+1):
                if j < nums[i-1]:
                    dp[i][j] = dp[i-1][j]
                else:
                    dp[i][j] = max(dp[i-1][j-nums[i-1]]+nums[i-1], dp[i-1][j])
        # print(dp)
        return dp[-1][-1] == target
canPartition([22,])

True

In [109]:
# 322
def coinChange(coins, amount):
    dp = [[float('inf') for _ in range(amount+1)] for _ in range(len(coins)+1)]
    for i in range(len(coins)+1):
        for j in range(amount+1):
            if j == 0:
                dp[i][j] = 0
    for i in range(1, len(coins)+1):
        for j in range(1, amount+1):
            if j-coins[i-1] < 0:
                dp[i][j] = dp[i-1][j]        
            else:
                dp[i][j] = min(dp[i-1][j], dp[i][j-coins[i-1]]+1)  
    if dp[-1][-1] == float('inf'):
        return -1
    return dp[-1][-1]
print(coinChange([6, 2], 7))
# print(k_sum([3,6], 8))
# print(k_sum([2,5,10,1], 27))
# print(k_sum([3,6], 10))
# print(k_sum([3,6], 11))
# print(k_sum([3,6], 12))
# print(k_sum([3,6], 13))
# print(k_sum([3,6], 14))


-1


In [94]:
def coinChange(coins, amount):
    """
    :type coins: List[int]
    :type amount: int
    :rtype: int
    """
    dp=[-1]*(amount+1)
    dp[0]=0
    for i in range(1,amount+1):
        for j in range(0,len(coins)):
            if i>=coins[j] and dp[i-coins[j]]!=-1:
                if dp[i]==-1 or dp[i]>dp[i-coins[j]]+1:
                    dp[i]=dp[i-coins[j]]+1
    print(dp)
    return dp[amount]
# coinChange([2,5,10,1], 27)
print(k_sum([1, 2, 5], 11))

[0, 1, 1, 2, 2, 1, 2, 2, 3, 3, 2, 3]
3


In [86]:
def coinChange(coins, amount):
    """
    :type coins: List[int]
    :type amount: int
    :rtype: int
    """ 
    mem = [float('inf')]*(amount+1)
    mem[0] = 0
    for coin in coins:
        for j in range(coin, amount+1):
            mem[j] = min(mem[j], mem[j - coin] + 1) #这个像是竖着填表 先得到每一列最小的，再用这个去算右面的
        print(mem)
    return -1 if mem[-1] > amount else mem[-1]
print(coinChange([1, 2, 5], 11))
# coinChange([2,5,10,1], 27)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6]
[0, 1, 1, 2, 2, 1, 2, 2, 3, 3, 2, 3]
3


In [27]:
#647 计算这个字符串中有多少个回文子串
# "abc"输出: 3 解释: 三个回文子串: "a", "b", "c".
#  "aaa"输出: 6 说明: 6个回文子串: "a", "a", "a", "aa", "aa", "aaa".
def countSubstrings(s):
    """
    :type s: str
    :rtype: int
    """
    dp = [i+1 for i in range(len(s))]
    for i in range(1, len(s)):
        count = 0
        dp[i] = dp[i-1] + 1   #每一个都是前面+1个基础上  再算和前面哪个组成回文子串 组成一个就加1
        for j in range(i):
            if s[j:i+1] == s[j:i+1][::-1]:
                count += 1
        dp[i] += count
#     print(dp)
    return dp[-1]
countSubstrings('abc')

3

In [32]:
#648. 单词替换
#输入: dict(词典) = ["cat", "bat", "rat"]
# sentence(句子) = "the cattle was rattled by the battery"
# 输出: "the cat was rat by the bat"
def replaceWords(dict, sentence): #变成list 原地修改后 再组合回来
    """
    :type dict: List[str]
    :type sentence: str
    :rtype: str
    """
    sen = sentence.split()
    # ret = []
    dict.sort(key=len)
    for i in range(len(sen)):
        for word in dict:
            if sen[i].startswith(word):
                sen[i] = sen[i][:len(word)]
                # ret.append(c)
                break
    return ' '.join(sen)

In [13]:
#343 整数拆分
def integerBreak(n):
    dp = [0 for _ in range(n+1)]
    if n == 2:
        return 1
    elif n == 3:
        return 2
    else:
        dp[2] = 1
        dp[3] = 2
        for i in range(4, n+1):
            dp[i] = max((n-2) * 2, (n-3)*3, dp[i-2]*2, dp[i-3]*3) #如果最大值是dp的  就是说明是前面堆起来的再*2
        print(dp)                                        #或者可能直接是(n-2)*2 (n-3)*3
    return dp[-1]
integerBreak(7)

[0, 0, 1, 2, 12, 12, 24, 36]


36

In [ ]:
#377. 组合总和 Ⅳ
def combinationSum4(nums, target):
    dp = [[[] for _ in range(target+1)] for _ in range(len(nums)+1)]
    

In [16]:
def canPartitionKSubsets(nums, k):
    """
    :type nums: List[int]
    :type k: int
    :rtype: bool
    """
    if len(nums) < k:
        return False
    elif len(nums) == k:
        flag = 0
        for k in range(len(nums)-1):
            if nums[k] == nums[k+1]:
                flag += 1
        if flag == len(nums) - 1:
            return True
        else:
            return False
    ret = nums[:k]
    for i in range(k, len(nums)):
        flag = 0
        ret.append(nums[i])
        ret.sort()
        a1 = ret.pop(0)
        a2 = ret.pop(0)
        ret.append(a1+a2)
#         print(ret)
        for k in range(len(ret)-1):
            if ret[k] == ret[k+1]:
                flag += 1
        if flag == len(ret) - 1:
            return True 
    return False
canPartitionKSubsets([1,1,1,2,2,1], k = 4)

True

In [7]:
# 定义状态：dp[i][j]:第一个串的第i个位置与第二个串的第j个位置之前需要操作几次达到相等。
# 之后，如果word1[i] = word2[j]，如果相等的话，那么就不用替换，也不要增删，操作次数直接等于dp[i-1][j-1]。
# 如果不等于：那么就有三种情况，
# 一种是删删第一个串一个字符到状态dp[i-1][j]，
# 第二中是删第二个串一个字符到dp[i][j-1]，
# 第三种是替换一个字符使得两个字符相等。这三种操作都只进行一次。
# 那么转移方程为：dp[i][j] = min(dp[i-1][j-1],min(dp[i-1][j],dp[i][j-1]))+1;
# 72 题 编辑距离
def minDistance(word1, word2):
    n = len(word1)
    m = len(word2)

    dp = [[0]*(m+1) for x in range(n+1)]     #dp[i][j]是word1的长度i位置替换world2的长度j位置所需要的编辑距离

    for i in range(0,n+1):
        for j in range(0,m+1):
            if i == 0:
                dp[0][j] = j
            elif j ==0:
                dp[i][0] = i
            else:
                if word1[i-1] == word2[j-1]:
                    dp[i][j] = dp[i-1][j-1]

                else:
                    dp[i][j] = min(dp[i-1][j-1], dp[i-1][j], dp[i][j-1])+ 1
    for i in dp:
        print(i)
    return dp[n][m]
minDistance('horse', 'ros')

[0, 1, 2, 3]
[1, 1, 2, 3]
[2, 2, 1, 2]
[3, 2, 2, 2]
[4, 3, 3, 2]
[5, 4, 4, 3]


3

In [12]:
def pack1(w, v, C): #每个东西只能选择一次
    dp = [[float('-inf') for _ in range(C+1)] for _ in range(len(w)+1)]
    for i in range(len(w)+1):
        for j in range(C+1):
            if j==0:
                dp[i][j] = 0
#     dp[0][0] = 0
    for i in range(1, len(w)+1):
        for j in range(1, C+1):
            if j < w[i-1]:
                dp[i][j] = dp[i-1][j]
            else:
                dp[i][j] = max(dp[i-1][j], dp[i-1][j-w[i-1]]+ v[i-1])
#     print(dp)
    for i in dp:
        print(i)
# pack1([2,2,6,5,4], [6,3,5,4,6], 10)
# print('')
pack1([2,3,6,5], [3,4,5,6], 10)

[0, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf]
[0, -inf, 3, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf]
[0, -inf, 3, 4, -inf, 7, -inf, -inf, -inf, -inf, -inf]
[0, -inf, 3, 4, -inf, 7, 5, -inf, 8, 9, -inf]
[0, -inf, 3, 4, -inf, 7, 5, 9, 10, 9, 13]


In [13]:
class Solution: #TL
    def findTargetSumWays(self, nums, S):
        """
        :type nums: List[int]
        :type S: int
        :rtype: int
        """
        s = (sum(nums) + S) // 2
        if 2 * s != sum(nums)+S:
            return 0
        dp = [float('-inf') for _ in range(int(s)+1)]
        ret = [0 for _ in range(s+1)]
        ret[0] = 1
        dp[0] = 0
        for i in range(1, len(nums)+1):
            for j in reversed(range(s+1)):
                if j-nums[i-1] >= 0:
                    ss = max(dp[j], dp[j-nums[i-1]]+nums[i-1])
                    temp = 0
                    if dp[j] == ss:
                        temp += ret[j]
                    if dp[j-nums[i-1]]+nums[i-1] ==  ss:
                        temp += ret[j-nums[i-1]]
                    dp[j] = ss
                    ret[j] = temp
#                     print(temp)
#             print(ret)
        return ret[-1]
#         print(ret)
#         print(dp)
# Solution().findTargetSumWays([1,1,1,1,1], 3)
Solution().findTargetSumWays([1], 2)

0

In [5]:
class Solution:
    def findTargetSumWays(self, nums, S):
        """
        :type nums: List[int]
        :type S: int
        :rtype: int
        """
        sum_nums = sum(nums)
        if sum_nums < S or (S + sum_nums)%2 != 0:
            return 0

        target = (S + sum_nums) >> 1
        mem = [0]*(target + 1)
        mem[0] = 1
        for num in nums:
#             for i in range(target, num-1, -1):
            for i in range(num, target+1):
                mem[i] += mem[i - num]
            print(mem)
        return mem[target]
Solution().findTargetSumWays([1,1,1,1,1], 3)

[1, 1, 1, 1, 1]
[1, 2, 3, 4, 5]
[1, 3, 6, 10, 15]
[1, 4, 10, 20, 35]
[1, 5, 15, 35, 70]


70

In [7]:
def zuhe_shu(nums, target):
    mem = [0]*(target + 1)
    mem[0] = 1
    for num in nums:
    #             for i in range(target, num-1, -1):
        for i in range(num, target+1):
            mem[i] += mem[i - num]
        print(mem)
    return mem[target]
zuhe_shu([1,2,3], 4)

[1, 1, 1, 1, 1]
[1, 1, 2, 2, 3]
[1, 1, 2, 3, 4]


4

In [1]:
#最长公共子序列 ，给定连个字符串 求最长的相交的，可以不连续
def long(A, B):
    dp = [[0 for _ in range(len(B)+1)] for _ in range(len(A)+1)]
    ret = [['' for _ in range(len(B)+1)] for _ in range(len(A)+1)]
    for i in range(1, len(A)+1):
        for j in range(1, len(B)+1):
            if A[i-1] == B[j-1]:
#                 ret += A[i-1]
                if i-1 >= 0 and j-1 >= 0:
                    dp[i][j] = dp[i-1][j-1] + 1
                    ret[i][j] = ret[i-1][j-1] + A[i-1]
            else:
                if dp[i][j-1]>dp[i-1][j]:
                    dp[i][j] = dp[i][j-1]
                    ret[i][j] = ret[i][j-1]
                else:
                    ret[i][j] = ret[i-1][j]
                    dp[i][j] = dp[i-1][j]
    for i in range(len(ret)):
        print(ret[i])
        print(dp[i])
#     print(dp)
long('BDCABA', "ABCBDAB")

['', '', '', '', '', '', '', '']
[0, 0, 0, 0, 0, 0, 0, 0]
['', '', 'B', 'B', 'B', 'B', 'B', 'B']
[0, 0, 1, 1, 1, 1, 1, 1]
['', '', 'B', 'B', 'B', 'BD', 'BD', 'BD']
[0, 0, 1, 1, 1, 2, 2, 2]
['', '', 'B', 'BC', 'BC', 'BD', 'BD', 'BD']
[0, 0, 1, 2, 2, 2, 2, 2]
['', 'A', 'B', 'BC', 'BC', 'BD', 'BDA', 'BDA']
[0, 1, 1, 2, 2, 2, 3, 3]
['', 'A', 'AB', 'BC', 'BCB', 'BCB', 'BDA', 'BDAB']
[0, 1, 2, 2, 3, 3, 3, 4]
['', 'A', 'AB', 'BC', 'BCB', 'BCB', 'BCBA', 'BDAB']
[0, 1, 2, 2, 3, 3, 4, 4]
