In [2]:
#递归方法  打家劫舍（只能取相邻的，找最大值）
def rec_dp(arr, i):
    if i == 0:
        return arr[i]
    elif i == 1:
        return max(arr[0], arr[1])
    else:
        A = rec_dp(arr, i-2) + arr[i] #选中当前这个值，结果是当前值加上i-2时的最优值
        B = rec_dp(arr, i-1)
        return max(A, B)
rec_dp([1,2,4,1,7,8,3], 6)

15

In [4]:
#由于递归方法复杂度高2**n （由于不存中间数，每个都重新计算） 一般改成不是递归的
import numpy as np
def dp(arr):
    opt = np.zeros(len(arr))
    opt[0] = arr[0]
    opt[1] = max(arr[0], arr[1])
    for i in range(2, len(arr)):
        A = opt[i-2] + arr[i]
        B = opt[i-1]
        opt[i] = max(A, B)
    print(opt)
    return opt[i]
dp([1,2,4,1,7,8,3])

[  1.   2.   5.   5.  12.  13.  15.]


15.0

In [9]:
##斐波那契数列 [1,1,2,3,5,8]
def fib(i):
    if i == 0 or i == 1:
        return 1
    else:
        return fib(i-1) + fib(i-2)
fib(5)

8

In [19]:
# import numpy as np
def fib1(i):
    i = i+1
    opt = np.zeros(i)
    opt = [0 for _ in range(i)]
    opt[0], opt[1] = 1,1
    for k in range(2, i):
        opt[k] = opt[k-1] + opt[k-2]
    print(opt)
    return opt[k]
fib1(5)

[1, 1, 2, 3, 5, 8]


8

In [4]:
# k_sum 是否存在数加起来可以得到target
def k_sum(nums, i, target):
    if target == 0:
        return True
    elif i == 0:
        return nums[i] == target
    elif nums[i] > target:
        return k_sum(nums, i-1, target)
    else:
        A = k_sum(nums, i-1, target)
        B = k_sum(nums, i-1, target - nums[i])
        return A or B
    
    
def k_sum2(nums, target):
    import numpy as np
    subset = np.zeros((len(nums), target+1), dtype=bool)
    subset[:, 0] = True
    
    subset[0, :] = False
    subset[0, nums[0]] = True
    subset[0, 0] = True
    for i in range(1, len(nums)):
        for s in range(1, target+1):
            if nums[i] > s:
                subset[i, s] = subset[i-1, s]
            else:
                A = subset[i-1, s]
                B = subset[i-1, s-nums[i]]
                subset[i, s] = A or B
#     print(subset)
    return subset[i, s]
print(k_sum([3, 34, 4, 12, 5, 2],  5, 9))
print(k_sum([3, 34, 4, 12, 5, 2],  5, 10))
print(k_sum([3, 34, 4, 12, 5, 2],  5, 11))
print(k_sum([3, 34, 4, 12, 5, 2],  5, 12))
print(k_sum([3, 34, 4, 12, 5, 2],  5, 13))

print(k_sum2([3, 34, 4, 12, 5, 2], 9))
print(k_sum2([3, 34, 4, 12, 5, 2], 10))
print(k_sum2([3, 34, 4, 12, 5, 2], 11))
print(k_sum2([3, 34, 4, 12, 5, 2], 12))
print(k_sum2([3, 34, 4, 12, 5, 2], 13))

True
True
True
True
False
True
True
True
True
False


## dfs， bfs

## 


![title](img/2.jpg)

In [3]:
graph = {'A': ['B', 'C'],   #图用字典表示
         'B': ['A', 'C', 'D'], 
         'C': ['A', 'B', 'D', 'E'], 
         'D': ['B', 'C', 'E', 'F'], 
         'E':['C', 'D'], 
         'F':['D']}

In [12]:
def bfs(graph, s):  #建立一个队列 只有队列有节点，pop出来节点 然后看他的所有连接节点，如果是没见过的节点
    queue = []      #就append到stack里面 
    queue.append(s)
    seen_node = [s]
    while queue:
        node = queue.pop(0)
        for node_single in graph[node]:
            if node_single not in seen_node:
                queue.append(node_single)
                seen_node.append(node_single)
        print(node, end='')
bfs(graph, 'A')
print('')
bfs(graph, 'E')

ABCDEF
ECDABF

In [18]:
def dfs(graph, s):  #直接把队列改成栈就完事了，别的啥都不用改
    stack = [s]  
    seen_node = [s]
    while stack:
        node = stack.pop()
        for node_single in graph[node]:
            if node_single not in seen_node:
                stack.append(node_single)
                seen_node.append(node_single)
        print(node, end='')   
dfs(graph, 'A')
print('')
dfs(graph, 'E')

ACEDFB
EDFBAC

In [34]:
def dfs(graph, s):   #拓展， 寻找最短路径
    stack = [s]  
    seen_node = [s]
    parent = {s: None}
    while stack:
        node = stack.pop(0)    # ######### 加0 是E -> C -> B 不加0 是 E -> D -> B
        for node_single in graph[node]:
            if node_single not in seen_node:
                stack.append(node_single)
                seen_node.append(node_single)
                parent[node_single] = node
        print(node, end='')   
    return parent
# dfs(graph, 'A')
# print('')
parent = dfs(graph, 'E')  #得到储存所有上一步节点的字典  算E -> B的最短路径
print('') 
print(parent)
# for i, j in parent.items():
#     print(i, j)
v = 'B'
while v!=None:
    print(v)
    v = parent[v]
    

ECDABF
{'E': None, 'C': 'E', 'D': 'E', 'A': 'C', 'B': 'C', 'F': 'D'}
B
C
E


## 带距离的最短路径

![title](img/1.png)

In [37]:
import heapq
graph = {'A': {'B':5, 'C':1},   #图用字典表示
         'B': {}'A':5, 'C', 'D'}, 
         'C': ['A', 'B', 'D', 'E'], 
         'D': ['B', 'C', 'E', 'F'], 
         'E':['C', 'D'], 
         'F':['D']}


In [39]:
a = []
heapq.heappush(a, (3, 'A'))
a

[(3, 'A')]

In [51]:
import heapq
import math
graph = {'A': {'B':5, 'C':1},   #图用字典表示
         'B': {'A':5, 'C':2, 'D':1}, 
         'C': {'A':1, 'B':2, 'D':4, 'E':8}, 
         'D': {'B':1, 'C':4, 'E':3, 'F':6}, 
         'E':{'C':8, 'D':3}, 
         'F':{'D':6}}

def init_distance(graph, s):
	distance = {s:0}
	for i in graph.keys():
		if i is not s:
			distance[i] = math.inf
	return distance

def short_path(graph, s):
	pqueue = []
	heapq.heappush(pqueue, (0, s))
	parent = {s:None}
	distance = init_distance(graph, s)
	seen = []
	while pqueue:
		dist, vertex = heapq.heappop(pqueue)
		seen.append(vertex)  #只能说明父节点处理过了，每个子节点都要再处理 
		for w in graph[vertex].keys():
			if w not in seen:
				if dist + graph[vertex][w] < distance[w]:
					distance[w] = dist + graph[vertex][w]
					heapq.heappush(pqueue, (dist+graph[vertex][w], w))
					parent[w] = vertex
	return parent, distance
parent, distance = short_path(graph, 'A')
print(parent)
print(distance)

{'A': None, 'B': 'C', 'C': 'A', 'D': 'B', 'E': 'D', 'F': 'D'}
{'A': 0, 'B': 3, 'C': 1, 'D': 4, 'E': 7, 'F': 10}


In [50]:
## 求出内个最短的路径  （这是反向的）
v = 'F' 
while v is not None:
    print(v)
    v = parent[v]

F
D
B
C
A


In [11]:
def maxSubArray(nums):  
    """ 
    :type nums: List[int] 
    :rtype: int 
    """  
    length=len(nums)  
    for i in range(1,length):  
        #当前值的大小与前面的值之和比较，若当前值更大，则取当前值，舍弃前面的值之和  
        subMaxSum=max(nums[i]+nums[i-1],nums[i])  
        nums[i]=subMaxSum#将当前和最大的赋给nums[i]，新的nums存储的为和值  
    print(nums)
    return max(nums) 
maxSubArray([1,2,-2,4,1])

[1, 3, 1, 5, 6]


6

In [8]:
def max_sub(nums):
    cur_sum = 0
    max_sum = nums[0]
    for i in range(len(nums)):
        cur_sum += nums[i]
        max_sum = max(cur_sum, max_sum)
        if cur_sum < 0: #如果当前和<0 说明前面全不能用
            cur_sum = 0
        print(max_sum)
max_sub([1,2,-2,4,-2, 1])

1
3
3
5
5
5


In [21]:
def max_square(nums):
    import numpy as np
    raw = len(nums)
    col = len(nums[0])
    dp = np.zeros_like(nums, dtype=int)
    up = np.zeros((raw, col))
    left = np.zeros((raw, col))
    for i in range(len(nums)):
        for j in range(len(nums[0])):
            l_value = 0
            u_value = 0
            k = j
            while k>=0 and nums[i][k] == '1':
                k -= 1
                l_value += 1
#             print(l_value)
#             print('j', j)
            left[i][j] = l_value
            q = i
            while q>=0 and nums[q][j] == '1':
                q -= 1
                u_value += 1
            up[i][j] = u_value
    dp[0][0] = nums[0][0]
    for i in range(1, raw):
        for j in range(1, col):
#             bian = 
            dp[i, j] = min(dp[i-1, j-1]+1, left[i, j], up[i, j])
#     print(left)
#     print(up)
#     print(dp)
    return dp.max()

max_square([["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]])

#     for i in range()

[[ 1.  0.  1.  0.  0.]
 [ 1.  0.  1.  2.  3.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  0.  0.  1.  0.]]
[[ 1.  0.  1.  0.  0.]
 [ 2.  0.  2.  1.  1.]
 [ 3.  1.  3.  2.  2.]
 [ 4.  0.  0.  3.  0.]]
[[1 0 0 0 0]
 [0 0 1 1 1]
 [0 1 1 2 2]
 [0 0 0 1 0]]


2

In [19]:
import numpy as np
help(np.zeros_like)

Help on function zeros_like in module numpy.core.numeric:

zeros_like(a, dtype=None, order='K', subok=True)
    Return an array of zeros with the same shape and type as a given array.
    
    Parameters
    ----------
    a : array_like
        The shape and data-type of `a` define these same attributes of
        the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.
    
        .. versionadded:: 1.6.0
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible.
    
        .. versionadded:: 1.6.0
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of 'a', otherwise it will be a base-class array. Defaults
        to True.
    
    Returns
    -------
    out : ndarray
  